### ISSUE TITLE
LIR passes tracking issue

### ISSUE THREAD

**Issue by walterpie** [ampersand-lang/etc-rs#12]
- [ ] analyze_verify (#1)
- [ ] analyze_loop (#2)
- [ ] optimize_loop_unroll (#7)
- [ ] optimize_cfg_simplify (#11)
- [ ] optimize_alloca_elim (#4)
- [ ] analyze_side_effect (#3)
- [ ] optimize_reassociate (#9)
- [ ] optimize_common_subexpr (#10)
- [ ] optimize_instr_combine (#8)
- [ ] optimize_dead_code (#6)
- [ ] optimize_const_fold (#5)
